# Variables, arithmetic, printing, interpolation
int x = 5;
float y = 2.5;
char c = 'e';
string s = "emerald";
print(x);
print(y);
print(c);
print(s);
print("x={x} y={y} c={c} s={s}");
print(x + y);
print(x * 2, " ", x - 3, " ", x + 100);
int q = 17;
print(q / 5);
print(q // 5);
print(q % 5);
print(2 ** 8);
print(floor(3.9), " ", top(3.1), " ", abs(-7), " ", abs(-2.5));
print(log(1000));
print(log(2, 8));
print(ln(1));
print(sqrt(49));
print(sin(0), " ", cos(0));
print(sinh(0), " ", tanh(0));
string t = "con" + "cat" + "enate";
print(t);
print(len(s), " ", len(x), " ", len(2.5), " ", len('a'));
print(nil == nil);
int uninit;
float funinit;
string suninit;
print(uninit, " ", funinit, " [", suninit, "]");
